language: java
jdk:
  - openjdk11
script:
  - mvn -P codecoverage clean package sonar:sonar
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: "alinkov-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
